// MIDI instrument numbers, 0-origin
#define I_Acoustic_Grand 0 
#define I_Bright_Acoustic 1 
#define I_Electric_Grand 2 
#define I_HonkyTonk 3 
#define I_Electric_Piano_1 4 
#define I_Electric_Piano_2 5 
#define I_Harpsichord 6 
#define I_Clav 7 
#define I_Celesta 8 
#define I_Glockenspiel 9 
#define I_Music_Box 10 
#define I_Vibraphone 11 
#define I_Marimba 12 
#define I_Xylophone 13 
#define I_Tubular_Bells 14 
#define I_Dulcimer 15 
#define I_Drawbar_Organ 16 
#define I_Percussive_Organ 17 
#define I_Rock_Organ 18 
#define I_Church_Organ 19 
#define I_Reed_Organ 20 
#define I_Accordion 21 
#define I_Harmonica 22 
#define I_Tango_Accordion 23 
#define I_Acoustic_Guitar_nylon 24 
#define I_Acoustic_Guitar_steel 25 
#define I_Electric_Guitar_jazz 26 
#define I_Electric_Guitar_clean 27 
#define I_Electric_Guitar_muted 28 
#define I_Overdriven_Guitar 29 
#define I_Distortion_Guitar 30 
#define I_Guitar_Harmonics 31 
#define I_Acoustic_Bass 32 
#define I_Electric_Bass_finger 33 
#define I_Electric_Bass_pick 34 
#define I_Fretless_Bass 35 
#define I_Slap_Bass_1 36 
#define I_Slap_Bass_2 37 
#define I_Synth_Bass_1 38 
#define I_Synth_Bass_2 39 
#define I_Violin 40 
#define I_Viola 41 
#define I_Cello 42 
#define I_Contrabass 43 
#define I_Tremolo_Strings 44 
#define I_Pizzicato_Strings 45 
#define I_Orchestral_Harp 46 
#define I_Timpani 47 
#define I_String_Ensemble_1 48 
#define I_String_Ensemble_2 49 
#define I_SynthStrings_1 50 
#define I_SynthStrings_2 51 
#define I_Choir_Aahs 52 
#define I_Voice_Oohs 53 
#define I_Synth_Voice 54 
#define I_Orchestra_Hit 55 
#define I_Trumpet 56 
#define I_Trombone 57 
#define I_Tuba 58 
#define I_Muted_Trumpet 59 
#define I_French_Horn 60 
#define I_Brass_Section 61 
#define I_SynthBrass_1 62 
#define I_SynthBrass_2 63 
#define I_Soprano_Sax 64 
#define I_Alto_Sax 65 
#define I_Tenor_Sax 66 
#define I_Baritone_Sax 67 
#define I_Oboe 68 
#define I_English_Horn 69 
#define I_Bassoon 70 
#define I_Clarinet 71 
#define I_Piccolo 72 
#define I_Flute 73 
#define I_Recorder 74 
#define I_Pan_Flute 75 
#define I_Blown_Bottle 76 
#define I_Shakuhachi 77 
#define I_Whistle 78 
#define I_Ocarina 79 
#define I_Lead_1__square 80 
#define I_Lead_2__sawtooth 81 
#define I_Lead_3__calliope 82 
#define I_Lead_4__chiff 83 
#define I_Lead_5__charang 84 
#define I_Lead_6__voice 85 
#define I_Lead_7__fifths 86 
#define I_Lead_8__bass_lead 87 
#define I_Pad_1__new_age 88 
#define I_Pad_2__warm 89 
#define I_Pad_3__polysynth 90 
#define I_Pad_4__choir 91 
#define I_Pad_5__bowed 92 
#define I_Pad_6__metallic 93 
#define I_Pad_7__halo 94 
#define I_Pad_8__sweep 95 
#define I_FX_1__rain 96 
#define I_FX_2__soundtrack 97 
#define I_FX_3__crystal 98 
#define I_FX_4__atmosphere 99 
#define I_FX_5__brightness 100 
#define I_FX_6__goblins 101 
#define I_FX_7__echoes 102 
#define I_FX_8__scifi 103 
#define I_Sitar 104 
#define I_Banjo 105 
#define I_Shamisen 106 
#define I_Koto 107 
#define I_Kalimba 108 
#define I_Bagpipe 109 
#define I_Fiddle 110 
#define I_Shanai 111 
#define I_Tinkle_Bell 112 
#define I_Agogo 113 
#define I_Steel_Drums 114 
#define I_Woodblock 115 
#define I_Taiko_Drum 116 
#define I_Melodic_Tom 117 
#define I_Synth_Drum 118 
#define I_Reverse_Cymbal 119 
#define I_Guitar_Fret_Noise 120 
#define I_Breath_Noise 121 
#define I_Seashore 122 
#define I_Bird_Tweet 123 
#define I_Telephone_Ring 124 
#define I_Helicopter 125 
#define I_Applause 126 
#define I_Gunshot 127 
